### PR TITLE
Added a 4 star rating badge

### PR DESCRIPTION
**Pull request by binhbbbb**
Hi, your component was tested and listed in our Vaadin Directory with a pretty high rating. We think it would be cool to have these badges in your project.

Binh

### CODE REVIEW

**Comment by RomainCscn** [comment]
Hi Binh,

First, thank you for the review! We are currently migrating our components to Polymer 3, this means that we are also rewriting the README. We will integrate the badge with the new release.

Thanks again,
Romain.

**Comment by binhbbbb** [comment]
Hi @RomainCscn,

Thanks for the reply. It's great to hear that myscript-math-web is migrating to Polymer 3.

Regards,
Binh

P/s: Sorry for the duplicate pull request. Please ignore it.

**Comment by binhbbbb** [comment]
Looks like you guys finally make a Polymer 3 release, congratulations!

Maybe you can have a look at this again?

**Comment by padewitte** [comment]
Hi Binh, thanks again for your review and this PR. we already add the badge. We did not use the PR but the content is there. Is that ok for you?

**Comment by binhbbbb** [comment]
Oh, my bad. I did not realize it was already there. You can close the ticket now.

Thanks!

**Pull request closed without merging**
